<?php

namespace JIPBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AnnonceRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends EntityRepository
{

    public function getAllAnnonces()
    {
        return $this->createQueryBuilder('d')
            ->addOrderBy('d.id', "DESC")
            ;
    }

}
